/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiCanvasesRouteImport } from './routes/api.canvases'
import { Route as ApiImagesRouteImport } from './routes/api.images'
import { Route as CanvasIdRouteImport } from './routes/canvas.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCanvasesIdRouteImport } from './routes/api.canvases.$id'
import { Route as ApiImagesIdRouteImport } from './routes/api.images.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasesRoute = ApiCanvasesRouteImport.update({
  id: '/api/canvases',
  path: '/api/canvases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIdRoute = CanvasIdRouteImport.update({
  id: '/canvas/$id',
  path: '/canvas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasesIdRoute = ApiCanvasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCanvasesRoute,
} as any)
const ApiImagesIdRoute = ApiImagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiImagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/canvases': typeof ApiCanvasesRouteWithChildren
  '/api/images': typeof ApiImagesRouteWithChildren
  '/canvas/$id': typeof CanvasIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvases/$id': typeof ApiCanvasesIdRoute
  '/api/images/$id': typeof ApiImagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/canvases': typeof ApiCanvasesRouteWithChildren
  '/api/images': typeof ApiImagesRouteWithChildren
  '/canvas/$id': typeof CanvasIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvases/$id': typeof ApiCanvasesIdRoute
  '/api/images/$id': typeof ApiImagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/canvases': typeof ApiCanvasesRouteWithChildren
  '/api/images': typeof ApiImagesRouteWithChildren
  '/canvas/$id': typeof CanvasIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/canvases/$id': typeof ApiCanvasesIdRoute
  '/api/images/$id': typeof ApiImagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/canvases'
    | '/api/images'
    | '/canvas/$id'
    | '/api/auth/$'
    | '/api/canvases/$id'
    | '/api/images/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/canvases'
    | '/api/images'
    | '/canvas/$id'
    | '/api/auth/$'
    | '/api/canvases/$id'
    | '/api/images/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/canvases'
    | '/api/images'
    | '/canvas/$id'
    | '/api/auth/$'
    | '/api/canvases/$id'
    | '/api/images/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiCanvasesRoute: typeof ApiCanvasesRouteWithChildren
  ApiImagesRoute: typeof ApiImagesRouteWithChildren
  CanvasIdRoute: typeof CanvasIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvases': {
      id: '/api/canvases'
      path: '/api/canvases'
      fullPath: '/api/canvases'
      preLoaderRoute: typeof ApiCanvasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$id': {
      id: '/canvas/$id'
      path: '/canvas/$id'
      fullPath: '/canvas/$id'
      preLoaderRoute: typeof CanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvases/$id': {
      id: '/api/canvases/$id'
      path: '/$id'
      fullPath: '/api/canvases/$id'
      preLoaderRoute: typeof ApiCanvasesIdRouteImport
      parentRoute: typeof ApiCanvasesRoute
    }
    '/api/images/$id': {
      id: '/api/images/$id'
      path: '/$id'
      fullPath: '/api/images/$id'
      preLoaderRoute: typeof ApiImagesIdRouteImport
      parentRoute: typeof ApiImagesRoute
    }
  }
}

interface ApiCanvasesRouteChildren {
  ApiCanvasesIdRoute: typeof ApiCanvasesIdRoute
}

const ApiCanvasesRouteChildren: ApiCanvasesRouteChildren = {
  ApiCanvasesIdRoute: ApiCanvasesIdRoute,
}

const ApiCanvasesRouteWithChildren = ApiCanvasesRoute._addFileChildren(
  ApiCanvasesRouteChildren,
)

interface ApiImagesRouteChildren {
  ApiImagesIdRoute: typeof ApiImagesIdRoute
}

const ApiImagesRouteChildren: ApiImagesRouteChildren = {
  ApiImagesIdRoute: ApiImagesIdRoute,
}

const ApiImagesRouteWithChildren = ApiImagesRoute._addFileChildren(
  ApiImagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiCanvasesRoute: ApiCanvasesRouteWithChildren,
  ApiImagesRoute: ApiImagesRouteWithChildren,
  CanvasIdRoute: CanvasIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
